### PR TITLE
add mutationobserver-shim and remove dataset to support ie10

### PR DESCRIPTION
**Pull request by dottodot**
Not sure if my method is perfect but as far as I can tell it works as before but also works in IE10.

### CODE REVIEW

**Comment by jesusbotella** [comment]
Let me give it a deeper look, but looks great!
I wrote down in my TODO list to reply your issue, but I have been very busy lately :(

I think it is good to have IE10 (and lower, maybe) support, but I don't know if the size increase of the bundle is worth to ship it to all users. I was thinking about creating another bundle version with higher browser compatibility for those developers who need it.

I will give it a look as soon as possible and will tell you what my thoughts are.
Thank you! 😁

**Comment by dottodot** [comment]
Would wrapping the require in a condition work. 

```
    if (this.ie10) {
      require('mutationobserver-shim');
    }
```
If so the module could have a config option added, something like
```
export const IE10 = new InjectionToken<boolean>('IE10');

@NgModule({
  declarations: [LazyLoadImagesDirective],
  exports: [LazyLoadImagesDirective]
})
export class LazyLoadImagesModule {
  public static forRoot(ie10?: boolean): ModuleWithProviders {
    return {
      ngModule: LazyLoadImagesModule,
      providers: [
        {
          provide: IE10,
          useValue: ie10
        }
      ]
    };
  }
}
```
I'm just not entirely sure if that would work in terms on not including `mutationobserver-shim` in the final build

**Comment by jesusbotella** [comment]
Yes, that wouldn't execute the `mutationobserver-shim` but wouldn't prevent it from being added to the bundle.

I have been thinking about this case and I came up with two solutions.

One solution would be to create a different bundle including the Mutation Observer for the users who want broader compatibility, supporting IE10 with the polyfill. So the users would have to require this special bundle instead of the regular one.

And the solution that I like the most, which is to use `getAttribute` to avoid the unsupported `dataset`property, and then let the users to require the MutationObserver polyfill that they want. They will have to code it like this:

```typescript
import 'mutationobserver-shim';
import { LazyLoadImagesModule } from 'ngx-lazy-load-images';
```

I think that the second solution is better because we let the users to choose the polyfill that they want. I have been searching for the best polyfill and I didn't see any clear winner as I saw with the `IntersectionObserver` polyfill.

What do you think?

**Comment by dottodot** [comment]
I think the second solution would be best as it gives the necessary flexibility and removes the need for you to maintain an extra bundle.

**Comment by jesusbotella** [comment]
Yes, I think so too. Would you mind updating the PR to adequate to this solution? :)

**Comment by dottodot** [comment]
OK that's done

**Comment by jesusbotella** [comment]
I think that the only changes that we need to keep are the ones from [`onImageAppearsInViewport()`](https://github.com/jesusbotella/ngx-lazy-load-images/pull/13/files#diff-c43dc51d938d3bdd10eca694cc0293c3R116), right? I prefer to not do any style modifications to the current code.

**Comment by dottodot** [comment]
Yes that's correct, I have prettier turned on so that's changed the style a bit.

**Pull request closed without merging**
