### PR TITLE
Update package to latest Angular version

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR is intended to update the module to be compatible with the latest Angular version.

### CODE REVIEW

**Comment by Mozart-Alkhateeb** [comment]
Hey there, thanks for the nice library, our previous team used this library in the project and we are migrating to angular 11 and we need to use Ivy, will this library get an update anytime soon ?

**Comment by jesusbotella** [comment]
Hello @Mozart-Alkhateeb!
I took some time today to publish a release candidate (`v2.0.0-rc2`) of the updated version.

Could you please take a look and tell me if it works for you?
You can install it with `npm i ngx-lazy-load-images@next`.

**Comment by Mozart-Alkhateeb** [comment]
Hello @jesusbotella,
Well thanks for the fast replay, really appreciated, I'll check it the soonest.

**Comment by jesusbotella** [comment]
I checked the release with Angular 9 and 11 and seems to be working good.
I released it as v2.0.0 version, please upgrade your `ngx-lazy-load-images` dependency in package.json to `^2.0.0`.

If you encounter any problems while using it, let me know or open a new issue please :)

**Comment by Mozart-Alkhateeb** [comment]
Everything works fine so far, Thanks for your efforts maintaining this library.

**Pull request closed without merging**
